const plugins = [
  ['Info', 'windows.info.Info', 'System'], ['Process list', 'windows.pslist.PsList', 'Windows'], ['Process scan', 'windows.psscan.PsScan', 'Windows'], ['Process tree', 'windows.pstree.PsTree', 'Windows'], ['Malfind', 'windows.malfind.Malfind', 'Windows'], ['Suspicious threads', 'windows.suspicious_threads.SuspiciousThreads', 'Windows'], ['Threads', 'windows.threads.Threads', 'All OS'], ['Network status', 'windows.netstat.NetStat', 'Windows'], ['Network scan', 'windows.netscan.NetScan', 'Windows'], ['Registry hives', 'windows.registry.hivelist.HiveList', 'Windows'], ['Command lines', 'windows.cmdline.CmdLine', 'Windows'], ['Timeline', 'timeliner.Timeliner', 'All OS']
];
const sampleRows = [{PID: '412', Process: 'systemd', PPID: '1', Image: '/sbin/init', CreateTime: '2026-09-07 08:12:04'}, {PID: '748', Process: 'sshd', PPID: '1', Image: '/usr/sbin/sshd', CreateTime: '2026-09-07 08:12:09'}, {PID: '1884', Process: 'firefox', PPID: '1442', Image: '/usr/lib/firefox/firefox', CreateTime: '2026-09-07 08:16:31'}, {PID: '2410', Process: 'python3', PPID: '1884', Image: '/tmp/.cache/update.py', CreateTime: '2026-09-07 08:22:46'}];
let selected = plugins[0], imageFile = null, evidenceRecord = null, currentRows = [], page = 1, pageSize = 8;
const resultsByPlugin = {};
const timelineRowsByPlugin = {};
const jobsByPlugin = {};
const pollTimersByPlugin = {};
const analysisControllersByPlugin = {};
function rowProcessId(row){ const key = Object.keys(row).find(name => /^(pid|processid|process\s*id)$/i.test(name)); return key && String(row[key]).trim(); }
function correlationRows(){ const malfindRows = resultsByPlugin['windows.malfind.Malfind'] || []; const suspiciousRows = resultsByPlugin['windows.suspicious_threads.SuspiciousThreads'] || []; const suspiciousByPid = new Map(); suspiciousRows.forEach(row => { const pid = rowProcessId(row); if(pid) suspiciousByPid.set(pid, [...(suspiciousByPid.get(pid) || []), row]); }); return malfindRows.flatMap(malfind => { const pid = rowProcessId(malfind); return pid && suspiciousByPid.has(pid) ? suspiciousByPid.get(pid).map(thread => ({PID: pid, Process: thread.Process || malfind.Process || 'Unknown process', Timestamp: thread.CreateTime || malfind.CreateTime || '', Correlation: 'Malfind + SuspiciousThreads', MemoryRegion: malfind['Start VPN'] || malfind.VadTag || malfind.Protection || 'Suspicious memory region', ThreadDetail: thread.Thread || thread.TID || thread.StartAddress || thread.State || 'Suspicious thread'})) : []; }); }
function updateCorrelationSignal(){ const matches = correlationRows(); $('triageSignal').textContent = matches.length ? `${matches.length} linked thread${matches.length === 1 ? '' : 's'}` : 'No linked findings'; }
const $ = id => document.getElementById(id);
function formatHistorySize(bytes){ return bytes >= 1024 * 1024 * 1024 ? `${(bytes / 1024 / 1024 / 1024).toFixed(1)} GB` : formatSize(bytes); }
async function refreshEvidenceHistory(){ const response = await fetch('/api/evidence'); const catalog = await response.json(); $('historyCount').textContent = catalog.items.length; $('historyList').innerHTML = catalog.items.map(item => `<div class="history-item"><button class="history-load" data-evidence="${encodeURIComponent(item.filename)}"><span class="history-icon">IMG</span><span><strong>${item.filename}</strong><small>${formatHistorySize(item.size)} · ${new Date(item.modified * 1000).toLocaleDateString()}</small></span></button><button class="icon-button history-delete" data-evidence="${encodeURIComponent(item.filename)}" aria-label="Delete ${item.filename}" title="Delete stored evidence">×</button></div>`).join('') || '<p class="history-empty">No stored captures yet.</p>'; document.querySelectorAll('.history-load').forEach(button => button.onclick = () => loadEvidence(decodeURIComponent(button.dataset.evidence))); document.querySelectorAll('.history-delete').forEach(button => button.onclick = () => deleteEvidence(decodeURIComponent(button.dataset.evidence))); }
async function loadEvidence(filename){ evidenceRecord = {filename}; imageFile = null; $('fileName').textContent = filename; $('fileSize').textContent = 'Stored locally'; $('fileCard').classList.remove('hidden'); $('dropZone').classList.add('hidden'); $('welcomePanel').classList.add('hidden'); $('caseFile').textContent = filename.toUpperCase(); setNotice('', false); selectPlugin(0); runAnalysis(); }
async function deleteEvidence(filename){ if(!confirm(`Delete stored evidence ${filename}? This cannot be undone.`)) return; const response = await fetch(`/api/evidence/${encodeURIComponent(filename)}`, {method:'DELETE'}); const result = await response.json(); if(!response.ok){ setNotice(result.error || 'Unable to delete evidence.'); return; } if(evidenceRecord && evidenceRecord.filename === filename){ evidenceRecord = null; imageFile = null; $('fileCard').classList.add('hidden'); $('dropZone').classList.remove('hidden'); $('caseFile').textContent = 'NO IMAGE LOADED'; } await refreshEvidenceHistory(); }
function renderPlugins(){ $('pluginList').innerHTML = plugins.map((plugin, index) => `<div class="plugin-row"><button class="plugin-button ${index === 0 ? 'active' : ''}" data-index="${index}"><span class="plugin-code">${String(index + 1).padStart(2,'0')}</span><span class="plugin-name">${plugin[0]}</span><span class="plugin-status" data-status-plugin="${plugin[1]}" aria-label="Not started">○</span></button><button class="plugin-run" data-index="${index}" aria-label="Run ${plugin[0]}" title="Run ${plugin[0]}">›</button></div>`).join(''); document.querySelectorAll('.plugin-button').forEach(button => button.onclick = () => selectPlugin(Number(button.dataset.index))); document.querySelectorAll('.plugin-run').forEach(button => button.onclick = event => { event.stopPropagation(); selectPlugin(Number(button.dataset.index)); runAnalysis(); }); }
function updatePluginStatus(pluginKey, status){ const indicator = document.querySelector(`[data-status-plugin="${pluginKey}"]`); if(!indicator) return; const labels = {starting:'Uploading', queued:'Queued', running:'Running', complete:'Complete', error:'Error', cancelled:'Cancelled'}; indicator.textContent = {starting:'◌', queued:'…', running:'◒', complete:'✓', error:'!', cancelled:'–'}[status] || '○'; indicator.dataset.state = status || 'idle'; indicator.setAttribute('aria-label', labels[status] || 'Not started'); }
function selectPlugin(index){ selected = plugins[index]; document.querySelectorAll('.plugin-button').forEach((button, i) => button.classList.toggle('active', i === index)); $('selectedPlugin').textContent = selected[0]; $('viewTitle').textContent = selected[0]; const savedRows = resultsByPlugin[selected[1]]; if(savedRows) renderTable(savedRows); else if(selected[1] !== 'windows.info.Info') renderTable([]); if(!$('timelineView').classList.contains('hidden')) renderTimeline(selected[1]); updateJobControls(); }
function updateJobControls(){ const job = jobsByPlugin[selected[1]]; const isRunning = job && (job.status === 'starting' || job.status === 'queued' || job.status === 'running'); const isComplete = job && job.status === 'complete'; updatePluginStatus(selected[1], job && job.status); $('cancelButton').classList.toggle('hidden', !isRunning); $('analysisProgress').classList.toggle('hidden', !isRunning && !isComplete); $('analysisProgress').classList.toggle('complete', isComplete); if(isRunning){ $('analysisState').textContent = 'Started'; $('lastActivity').textContent = job.message || 'Working'; } else if(isComplete){ $('analysisState').textContent = 'Complete'; $('lastActivity').textContent = job.message || 'Analysis complete'; } else { $('analysisState').textContent = imageFile ? 'Ready to run' : 'Ready'; $('lastActivity').textContent = imageFile ? 'Plugin not started' : 'Awaiting image'; } }
function setNotice(message, visible = true){ $('notice').textContent = message; $('notice').classList.toggle('hidden', !visible); }
function formatSize(bytes){ return `${(bytes / 1024 / 1024).toFixed(1)} MB`; }
function chooseFile(file){ if(!file) return; if(file.size > 2 * 1024 * 1024 * 1024){ setNotice('That image exceeds the 2 GB local limit.'); return; } imageFile = file; $('fileName').textContent = file.name; $('fileSize').textContent = formatSize(file.size); $('fileCard').classList.remove('hidden'); $('dropZone').classList.add('hidden'); $('welcomePanel').classList.add('hidden'); $('caseFile').textContent = file.name.toUpperCase(); $('analysisState').textContent = 'Ready to run'; $('analysisProgress').classList.add('hidden'); $('analysisProgress').classList.remove('complete'); $('lastActivity').textContent = 'Image loaded'; setNotice('', false); selectPlugin(0); runAnalysis(); }
function renderTable(rows, resetPage = true){ currentRows = rows; if(resetPage) page = 1; const discoveredKeys = [...new Set(rows.flatMap(row => Object.keys(row)))]; const infoKeys = ['Variable', 'Value'].filter(key => discoveredKeys.includes(key)); const keys = selected[1] === 'windows.info.Info' && infoKeys.length ? infoKeys : discoveredKeys.slice(0, 8); $('tableHead').innerHTML = `<tr>${keys.map(key => `<th>${key}</th>`).join('')}</tr>`; const query = $('searchInput').value.toLowerCase(); const filtered = rows.filter(row => Object.values(row).join(' ').toLowerCase().includes(query)); const selectedSort = $('sortSelect').value; const sorted = selectedSort === 'default' ? filtered : [...filtered].sort((a,b) => String(a[selectedSort]).localeCompare(String(b[selectedSort]))); const pages = Math.max(1, Math.ceil(sorted.length / pageSize)); page = Math.min(page, pages); const visible = sorted.slice((page - 1) * pageSize, page * pageSize); $('tableBody').innerHTML = visible.map(row => `<tr>${keys.map(key => `<td title="${String(row[key] ?? '')}">${row[key] ?? '—'}</td>`).join('')}</tr>`).join('') || `<tr><td colspan="${keys.length || 1}">No matching rows</td></tr>`; $('rowCount').textContent = rows.length.toLocaleString(); $('pageSummary').textContent = `Showing ${visible.length} of ${sorted.length} rows`; $('pageNumber').textContent = `${page} / ${pages}`; $('prevPage').disabled = page <= 1; $('nextPage').disabled = page >= pages; $('sortSelect').innerHTML = `<option value="default">Sort: original order</option>${keys.map(key => `<option value="${key}" ${key === selectedSort ? 'selected' : ''}>Sort: ${key}</option>`).join('')}`; $('resultView').classList.remove('hidden'); $('emptyState').classList.add('hidden'); }
function showLanding(){ $('welcomePanel').classList.remove('hidden'); $('resultsPanel').classList.add('landing-results'); $('analysisState').textContent = 'Ready'; $('analysisProgress').classList.add('hidden'); $('lastActivity').textContent = 'Awaiting image'; $('processSignal').textContent = '—'; $('networkSignal').textContent = '—'; $('triageSignal').textContent = 'Awaiting evidence'; }
function timelineRowsForPlugin(pluginKey, rows){ if(pluginKey === 'windows.malfind.Malfind' || pluginKey === 'windows.suspicious_threads.SuspiciousThreads'){ const matches = correlationRows(); const ids = new Set(matches.map(row => String(row.PID))); return rows.map(row => ids.has(String(rowProcessId(row))) ? {...row, Correlation: 'Linked with ' + (pluginKey === 'windows.malfind.Malfind' ? 'SuspiciousThreads' : 'Malfind')} : row); } return rows; }
function refreshPluginTimelines(){ Object.keys(resultsByPlugin).forEach(pluginKey => { timelineRowsByPlugin[pluginKey] = timelineRowsForPlugin(pluginKey, resultsByPlugin[pluginKey]); }); }
function renderTimeline(pluginKey = selected[1]){ const timelineRows = timelineRowsByPlugin[pluginKey] || []; const timestampKey = Object.keys(timelineRows[0] || {}).find(key => /time|date|timestamp/i.test(key)); const events = timelineRows.filter(row => (timestampKey && row[timestampKey]) || row.Correlation).slice(0, 80); const linked = timelineRows.filter(row => row.Correlation).length; $('timelineSummary').textContent = linked ? `${linked} linked finding${linked === 1 ? '' : 's'} in ${selected[0]}` : events.length ? `${events.length} timestamped events from ${selected[0]}` : 'No timestamped events in this plugin result'; $('timelineChart').innerHTML = events.map((row, index) => { const detail = Object.entries(row).filter(([key]) => key !== timestampKey).slice(0, 4).map(([key, value]) => `<span><b>${key}</b> ${value ?? '—'}</span>`).join(''); return `<article class="timeline-event"><div class="timeline-marker">${String(index + 1).padStart(2, '0')}</div><time>${row[timestampKey] || 'Time unavailable'}</time><div><strong>${row.Correlation || row.Description || row.Process || row.Event || 'Observed event'}</strong>${detail}</div></article>`; }).join('') || '<div class="timeline-empty">Run this plugin to populate its chronology.</div>'; }
function activateView(view){ const timeline = view === 'timeline'; $('tableView').classList.toggle('hidden', timeline); $('timelineView').classList.toggle('hidden', !timeline); $('resultsTab').classList.toggle('active', !timeline); $('timelineTab').classList.toggle('active', timeline); if(timeline) renderTimeline(selected[1]); }
async function runAnalysis(){ if(!imageFile && !evidenceRecord){ setNotice('Choose or load a memory image before running a plugin.'); return; } const pluginKey = selected[1]; const existingJob = jobsByPlugin[pluginKey]; if(existingJob && ['starting', 'queued', 'running'].includes(existingJob.status)) return; const controller = new AbortController(); analysisControllersByPlugin[pluginKey] = controller; jobsByPlugin[pluginKey] = {id: null, status: 'starting', message: imageFile ? 'Uploading image' : 'Opening stored image'}; $('analysisState').textContent = 'Started'; $('analysisProgress').classList.remove('hidden', 'complete'); setNotice('', false); updateJobControls(); try { let url = '/api/analyze'; let body; let headers; if(imageFile){ body = new FormData(); body.append('image', imageFile); body.append('plugin', pluginKey); } else { url = '/api/analyze-existing'; body = `filename=${encodeURIComponent(evidenceRecord.filename)}&plugin=${encodeURIComponent(pluginKey)}`; headers = {'Content-Type':'application/x-www-form-urlencoded'}; } const response = await fetch(url, {method:'POST', body, signal:controller.signal, headers}); if(!response.ok){ throw new Error(await response.text()); } const payload = await response.json(); if(payload.filename){ evidenceRecord = {filename: payload.filename}; await refreshEvidenceHistory(); } const id = payload.id; if(jobsByPlugin[pluginKey].status === 'cancelled') return; jobsByPlugin[pluginKey] = {id, status: 'queued', message: 'Queued'}; updateJobControls(); pollTimersByPlugin[pluginKey] = setInterval(() => pollJob(pluginKey), 700); } catch(error) { if(error.name !== 'AbortError' && jobsByPlugin[pluginKey].status !== 'cancelled'){ jobsByPlugin[pluginKey] = {status: 'error', message: error.message}; if(selected[1] === pluginKey) setNotice(error.message); } if(selected[1] === pluginKey) updateJobControls(); } finally { delete analysisControllersByPlugin[pluginKey]; } }
async function pollJob(pluginKey){ const jobState = jobsByPlugin[pluginKey]; if(!jobState) return; const job = await (await fetch(`/api/jobs/${jobState.id}`)).json(); jobsByPlugin[pluginKey] = {...jobState, ...job}; updatePluginStatus(pluginKey, job.status); if(selected[1] === pluginKey) updateJobControls(); if(job.status === 'complete'){ resultsByPlugin[pluginKey] = job.result.rows; refreshPluginTimelines(); updateCorrelationSignal(); if(selected[1] === pluginKey){ renderTable(job.result.rows); $('processSignal').textContent = selected[0].toLowerCase().includes('process') ? job.result.rows.length.toLocaleString() : '—'; $('networkSignal').textContent = selected[0].toLowerCase().includes('network') ? job.result.rows.length.toLocaleString() : '—'; $('triageSignal').textContent = correlationRows().length ? `${correlationRows().length} linked threads` : selected[0].toLowerCase().includes('malfind') ? `${job.result.rows.length} findings` : 'No alert yet'; updateJobControls(); } clearInterval(pollTimersByPlugin[pluginKey]); } else if(job.status === 'error' || job.status === 'cancelled'){ if(selected[1] === pluginKey){ setNotice(job.message); $('analysisProgress').classList.add('hidden'); } clearInterval(pollTimersByPlugin[pluginKey]); updateJobControls(); } }
async function cancelAnalysis(){ const pluginKey = selected[1]; const job = jobsByPlugin[pluginKey]; if(!job || !['starting', 'queued', 'running'].includes(job.status)) return; const controller = analysisControllersByPlugin[pluginKey]; if(controller) controller.abort(); if(job.id) await fetch(`/api/jobs/${job.id}`, {method:'DELETE'}); jobsByPlugin[pluginKey] = {...job, status: 'cancelled', message: 'Analysis cancelled'}; updateJobControls(); }
function bind(){ $('browseButton').onclick = () => $('fileInput').click(); $('welcomeBrowseButton').onclick = () => $('fileInput').click(); $('fileInput').onchange = event => chooseFile(event.target.files[0]); $('dropZone').ondragover = event => { event.preventDefault(); $('dropZone').classList.add('dragging'); }; $('dropZone').ondragleave = () => $('dropZone').classList.remove('dragging'); $('dropZone').ondrop = event => { event.preventDefault(); $('dropZone').classList.remove('dragging'); chooseFile(event.dataTransfer.files[0]); }; $('removeFile').onclick = () => { imageFile = null; evidenceRecord = null; $('fileCard').classList.add('hidden'); $('dropZone').classList.remove('hidden'); $('welcomePanel').classList.remove('hidden'); $('caseFile').textContent = 'NO IMAGE LOADED'; $('analysisState').textContent = 'Ready'; }; $('exportButton').onclick = () => { $('reportEvidence').textContent = evidenceRecord ? evidenceRecord.filename : imageFile ? imageFile.name : 'Not supplied'; $('reportPlugin').textContent = `${selected[0]} (${selected[1]})`; $('reportGenerated').textContent = new Date().toLocaleString(); $('printCase').textContent = evidenceRecord ? evidenceRecord.filename.toUpperCase() : imageFile ? imageFile.name.toUpperCase() : 'NO IMAGE LOADED'; window.print(); }; $('cancelButton').onclick = cancelAnalysis; $('resultsTab').onclick = () => activateView('results'); $('timelineTab').onclick = () => activateView('timeline'); $('searchInput').oninput = () => renderTable(currentRows); $('sortSelect').onchange = () => renderTable(currentRows); $('resetButton').onclick = () => { $('searchInput').value = ''; $('sortSelect').value = 'default'; renderTable(currentRows); }; $('prevPage').onclick = () => { if(page > 1){ page--; renderTable(currentRows, false); } }; $('nextPage').onclick = () => { page++; renderTable(currentRows, false); }; }
window.addEventListener('beforeprint', () => { if(currentRows.length){ pageSize = Math.max(currentRows.length, 8); renderTable(currentRows); } renderTimeline(selected[1]); });
window.addEventListener('afterprint', () => { pageSize = 8; if(currentRows.length) renderTable(currentRows); });
async function boot(){ renderPlugins(); bind(); showLanding(); refreshEvidenceHistory().catch(() => {}); try { const health = await (await fetch('/api/health')).json(); $('runtimeStatus').textContent = health.volatility ? 'Volatility engine detected' : 'Volatility engine not configured'; if(!health.volatility) setNotice('Volatility is not configured yet. Set VOLATILITY_PATH or place vol.py beside server.py to run live analysis.'); else setNotice('', false); } catch { $('runtimeStatus').textContent = 'Demo mode'; setNotice('The local engine is unavailable. Start server.py to run live analysis.'); } }
boot();